### ISSUE TITLE
scan networks doesn't work

### ISSUE THREAD

**Issue by trojek** [luqasz/librouteros#100]
I try to scan all networks on X wifi interface.
In routerOS I use command: `/interface wireless scan number=1`

Using librouteros I try to execute:
```
wireless = api.path('interface', 'wireless')
tuple(wireless('scan', **{'number': 1}))
```

but the above command doesn't return anything. How shoulde I librouteros in ordet to get all available networks?

**Comment by gil-obradors** [comment]
tuple(wireless('scan', **{'number': '***1'}))

maybe?

https://librouteros.readthedocs.io/en/latest/path.html#arbitrary-command

Missatge de Tomasz Rojek <notifications@github.com> del dia dv., 7 d’ag.
2020 a les 12:33:

**Comment by trojek** [comment]
Unfortunately it doesn't work.

**Comment by trojek** [comment]
The problem wasn't in librouteros but in the 'query'. Scan network is continuous operation, it ends when user hit the Q key. The solution is to add 'duration' paramter:
`tuple(wireless('scan', **{'number': 1, 'duration': 5}))`
