### ISSUE TITLE
Can't add security profile

### ISSUE THREAD

**Issue by trojek** [luqasz/librouteros#104]
I try to add a security profile. According to the docs: https://librouteros.readthedocs.io/en/latest/path.html I should do it like this:

```
security_profiles = api.path('interface', 'wireless', 'security-profiles')

security_profiles.add(authentication-types ='wpa-psk, wpa2-psk',
             eap-methods='',
             management-protection='allowed',
             mode='dynamic-keys',
             name='name',
             supplicant-identity='',
             wpa-pre-shared-key='pass',
             wpa2-pre-shared-key='pass'
             )
```

After execution I got an error:

```
    security_profiles.add(authentication-types ='wpa-psk, wpa2-psk',
                          ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
```
How can I add security profile?

**Comment by luqasz** [comment]
Does python allow variables or keywords to have `-` in them ?

**Comment by gil-obradors** [comment]
Hyphen is used as the subtraction operator, impossible to pass as kwargs

**Comment by trojek** [comment]
Is there any way to bypass this issue ?

I tried

```
security_profiles.add(**{authentication-types ='wpa-psk, wpa2-psk',
             eap-methods='',
             management-protection='allowed',
             mode='dynamic-keys',
             name='name',
             supplicant-identity='',
             wpa-pre-shared-key='pass',
             wpa2-pre-shared-key='pass'
})
```

based on https://stackoverflow.com/questions/24121279/python-keyword-arguments-with-hyphen but I get an error:
```    security_profiles.add(**{authentication-types ='wpa-psk, wpa2-psk',
                                                  ^
SyntaxError: invalid syntax
```

**Comment by luqasz** [comment]
You have add `SyntaxError`

**Comment by gil-obradors** [comment]
I don't know if it will work, but as Python basics.

try:
```
security_profiles.add(**{'authentication-types' : 'wpa-psk, wpa2-psk',
             'eap-methods' : '',
             'management-protection' : 'allowed',
...

```
Its common pass a dict instead of kwargs, if there's problems of syntaxis like that.
...but api must be compatible

**Comment by gil-obradors** [comment]
@trojek  If impossible to call add method as a dict like update... you can do a trick:

can you add a security profile only with a name ? 
Then....update with dict like [documentation](https://librouteros.readthedocs.io/en/latest/path.html#update)

**Comment by trojek** [comment]
Solution provied by @gil-obradors works. 

> I don't know if it will work, but as Python basics.
> 
> try:
> 
> ```
> security_profiles.add(**{'authentication-types' : 'wpa-psk, wpa2-psk',
>              'eap-methods' : '',
>              'management-protection' : 'allowed',
> ...
> ```
> 
> Its common pass a dict instead of kwargs, if there's problems of syntaxis like that.
> ...but api must be compatible
