### ISSUE TITLE
How to use set method?

### ISSUE THREAD

**Issue by trojek** [luqasz/librouteros#105]
I want to connect to a certain wifi network.
From ssh one can do: `/interface wireless> set wlan1 ssid=whatever`

Using librouteros I probably should use 'Arbitrary command'. In example I can find:

```
script = api.path('system', 'script')
# Will run /system/script/run with desired .id
tuple(script('run', **{'.id': '*1'}))
```

I try to connect using below code:
```
wireless = api.path('interface', 'wireless')
# Will run /system/script/run with desired .id
tuple(wireless('set wlan_client', **{'ssid': 'some_ssid', 'security-profile': 'some_sec_prof'}))
```

but I got: `librouteros.exceptions.TrapError: no such command`

How can I execute `set wlan1 ssid=whatever` in librouteros?

**Comment by luqasz** [comment]
`set wlan_client` is not a command, `set` is

**Comment by trojek** [comment]
What is `wlan1`? I assume that it is argument but I need to provide it in form of key value. Do you know what is the key?

**Comment by luqasz** [comment]
`wlan1` is a `name`. Look into cli and you will see what keywords API needs.
