### ISSUE TITLE
API incompatibility and print method

### ISSUE THREAD

**Issue by tarelda** [luqasz/librouteros#110]
1. Recently after upgrading bindings used by my automation script I soon realised that is not doing what is supposed to do. A little bit more digging afterwards I found out that simply calling api("/path/to/remove") doesn't work. Why? Because generator does not get resolved. I think API should not automatically assume that you wanna iterate over the command result. Especially if it is not print command. It is also breaking with very old version I was running previously.

2. IMHO, since Path object represents path in logical CLI structure and features conveniance methods like add, remove there should be also print method. Even as an alias to \_\_iter__.

**Comment by luqasz** [comment]
From https://semver.org

> Given a version number MAJOR.MINOR.PATCH, increment the:
>  MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards compatible manner, and
    PATCH version when you make backwards compatible bug fixes.

Version 3.x breaks API compatibility with 2.x

> 2 MHO, since Path object represents path in logical CLI structure and features conveniance methods like add, remove there should be also print method. Even as an alias to __iter__.

https://librouteros.readthedocs.io/en/latest/path.html

**Comment by tarelda** [comment]
> From https://semver.org
> 
> > Given a version number MAJOR.MINOR.PATCH, increment the:
> > MAJOR version when you make incompatible API changes,
> > MINOR version when you add functionality in a backwards compatible manner, and
> > PATCH version when you make backwards compatible bug fixes.
> 
> Version 3.x breaks API compatibility with 2.x
> 
> > 2 MHO, since Path object represents path in logical CLI structure and features conveniance methods like add, remove there should be also print method. Even as an alias to **iter**.
> 
> https://librouteros.readthedocs.io/en/latest/path.html

1. Remark about backward compatibility was only additional feedback. Mostly what I wanted to highlight is that interface that does not give warning that issued command was not resolved is counter intuitive to for example how futures work. My issue is that library does not execute command silently.

2. That is exactly what I am referencing. Iterator interface is nice syntactic sugar, but as a new interface's user I expected also print method since there are add/update/remove present.

**Comment by luqasz** [comment]
> 1 

Library won't emit any logging warning since almost noone reads them. [How to](https://librouteros.readthedocs.io/en/latest/path.html#arbitrary-command) execute silently.

> 2 
Ok. Please provide any docs update PR and if not, then please suggest what to fix / add.

Thx for feedback.
