### ISSUE TITLE
How to use max-limit= in this api

### ISSUE THREAD

**Issue by sxclll** [luqasz/librouteros#115]
Hello, I cant make work this - any escape charater dont allowed to add queue with parametr max-limit. Is some character change for "-"?

**Comment by luqasz** [comment]
Paste exact code.

**Comment by sxclll** [comment]
import librouteros

from librouteros import connect
from librouteros.login import plain, token

# for post 6.42 (plain text password)
# for pre 6.43 (with token)
method = token

api = connect(username='admin', password='example', host='any', login_method=method)

queue = api.path('/queue/simple')
queue.add(max-limit="10M/10M", name='test')

**Comment by luqasz** [comment]
This is python 101. Can you have variable names in python (or any other programming language) with `-` in them ?

**Comment by sxclll** [comment]
In routeros, the command is `/queue simple add max-limit=10M/20M name=name target=1.2.3.4/32` - unfortunately variable is with `-`. Any way to use your lib with simplq queue?

**Comment by luqasz** [comment]
https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments
