### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by zabuldon** [luqasz/librouteros#12]
In some cases I'm getting stackTrace when do the call cmd='/interface/wireless/registration-table/getall':
```python
  File "<stdin>", line 1, in <module>
  File "/opt/hass/lib/python3.5/site-packages/librouteros/api.py", line 81, in __call__
    return self._readResponse()
  File "/opt/hass/lib/python3.5/site-packages/librouteros/api.py", line 104, in _readResponse
    reply_word, words = self._readSentence()
  File "/opt/hass/lib/python3.5/site-packages/librouteros/api.py", line 90, in _readSentence
    words = dict(self.parseWord(word) for word in words)
  File "/opt/hass/lib/python3.5/site-packages/librouteros/api.py", line 90, in <genexpr>
    words = dict(self.parseWord(word) for word in words)
  File "/opt/hass/lib/python3.5/site-packages/librouteros/api.py", line 35, in parseWord
    _, key, value = word.split('=', 2)
```
I've dumped response from Mikrotik and looks like it returns broken data:
Normal response:
```
=signal-strength-ch0=-60
=signal-strength-ch1=-66
=strength-at-rates=-56@1Mbps 1m58s660ms,-58@5.5Mbps 39m49s430ms,-54@11Mbps 39m55s900ms,-51@HT20-0 40m1s630ms,-51@HT20-1 40m1s630ms,-58@HT20-2 2m50s680ms,-57@HT20-3 4m38s360ms,-55@HT20-4 4m33s320ms,-57@HT20-5 31m17s460ms,-50@HT20-6 18m48s650ms,-51@HT20-7 3s530ms
=tx-ccq=93
=p-throughput=59398
```
Broken response:
```
=signal-strength-ch0=-60
=signal-strength-ch1=-66
54@11Mbps 40m5s560ms,-51@HT20-0 40m11s290ms,-
```

Probably we can catch an exception and do a retry?

**Comment by zabuldon** [comment]
Issue in dependency:
https://github.com/luqasz/librouteros/issues/12

**Comment by luqasz** [comment]
Hi.

Thx for this bug report. 
```
=signal-strength-ch1=-66
54@11Mbps 40m5s560ms,-51@HT20-0 40m11s290ms,-
```
Did you get this response using debug in librouteros logger ? 
What routeros version are you running ?

**Comment by zabuldon** [comment]
I got this by dump from your code.
RouterOS is 6.40.1

So, it returns correct values in most of the cases. I don't see any correlations.. One thing which can I see it is error never repeat two and more times in a row.

**Comment by luqasz** [comment]
This is a bug in mikrotik API. Getting some "workaround fix" will require some weird operations and detecting those bugs on the fly. `6.40.1` is of "current" (I consider this dev) branch. Try updating routeros version or using "bugfix only". Do you know if other users have exactly same routeros version ? 

Looking at mikrotik [changelog](https://mikrotik.com/download/changelogs/#show-tab-tree_2-id-55220170c60eb7410613525ed72839ac) I suspect that they've introduced this in `6.40`
```
*) wireless - fixed registration table "signal-strength" reporting for chains when using nv2;
```

Can you please send them bug report. Feel free to link this issue if you want to.

**Comment by zabuldon** [comment]
@luqasz one of the users told he has exactly same version as me. I'm going to create bug in RouterOS bug tracking system, but I still waiting for email confirmation from their side.

**Comment by luqasz** [comment]
Ok. Try different routeros versions.

**Comment by luqasz** [comment]
@zabuldon  I have an idea. Can you give me read only access to your router ? I will query your router every N time and try to debug this. I suspect that this might be related to bad word encoding. If you are interested, please write ma an email (available in my github profile) so you can give me credentials there.

**Comment by zabuldon** [comment]
@luqasz Sure, no problem. But I can't find your email... Can you write me something? vortexius@gmail.com

**Comment by luqasz** [comment]
I can confirm that same happens on my routerboard with `6.38.7`

**Comment by luqasz** [comment]
After some debugging with ipdb I've found that this is a bug in my library. When a word is encoded with 2 bytes, second being `b'\x00'` [partition()](https://github.com/luqasz/librouteros/blob/1.0.3/librouteros/connections.py#L164) wrongly slices received data.

Sample data on which library fails:

```python
bytearray(b'\x03!re\n=.id=*14FC\x13=interface=wlan-lan\x1e=mac-address=7C:D1:C3:85:28:9E\t=ap=false\n=wds=false\r=bridge=false\x10=rx-rate=5.5Mbps\x18=tx-rate=78Mbps-20MHz/2S\x18=packets=5778484,6556890\x1b=bytes=6613722291,622318688\x17=frames=5778484,6557207!=frame-bytes=6625281205,583011289\x1a=hw-frames=6628257,6711423$=hw-frame-bytes=7783226984,849126983\x16=tx-frames-timed-out=0\x12=uptime=1d2h13m34s\x12=last-activity=0ms\x1a=signal-strength=-65@1Mbps\x13=signal-to-noise=50\x18=signal-strength-ch0=-66\x18=signal-strength-ch1=-70\x0b=evm-ch0=17\n=evm-ch1=7\x81\x00=strength-at-rates=-65@1Mbps 10ms,-65@2Mbps 90ms,-64@5.5Mbps 0ms,-65@6Mbps 2h3m43s,-64@12Mbps 440ms,-64@24Mbps 760ms,-63@HT20-0 110ms,-63@HT20-1 240ms,-63@HT20-2 270ms,-64@HT20-3 300ms,-63@HT20-4 320ms,-63@HT20-5 650ms,-63@HT20-6 5s870ms,-63@HT20-7 5s900ms\n=tx-ccq=63\x13=p-throughput=61744\x15=last-ip=192.168.1.90\x19=802.1x-port-enabled=true\x1d=authentication-type=wpa2-psk\x13=encryption=aes-ccm\x19=group-encryption=aes-ccm\x1c=management-protection=false\x11=wmm-enabled=true-=tx-rate-set=CCK:1-11 OFDM:6-54 BW:1x HT:0-15\x00\x05!done\x00')
```
"zoom" on data where it fails:
```
=evm-ch1=7\x81\x00=strength-at-rates=-65@1Mbps 10ms,
```
Note `\x81\x00`

Working on a fix.
