### ISSUE TITLE
Am i doing it right? or its a bug

### ISSUE THREAD

**Issue by markasena** [luqasz/librouteros#120]
`  def update_user_password(self, newName, new_password):

        for selected_user in self.secret.select(MKeys.id, MKeys.name, MKeys.password).where(MKeys.name == newName):
            print(selected_user)
            update_params = {'password': new_password, '.id': selected_user.get('.id')}
            print(selected_user)
            selected_user.update(**update_params)
            print(selected_user)`
   Changes are printed into the console but not affecting mikrotik secret, Can you help?

**Comment by luqasz** [comment]
What do you want to do ?
I don't get what's your goal.

**Comment by markasena** [comment]
Well by that statement i searched the user by name then want to change the password of that account by using the update but nothing changes.

**Comment by luqasz** [comment]
`password` field is considered secret and you will not see it. You can change it though.

**Comment by markasena** [comment]
How can i change that? i cant seem to find any options to do so.

**Comment by luqasz** [comment]
> How can i change that? i cant seem to find any options to do so.

Just like you do it now.

**Comment by markasena** [comment]
> > How can i change that? i cant seem to find any options to do so.
> 
> Just like you do it now.
adding and removing was no problem but changing or updating seems to fail for me. icant figure out why

**Comment by luqasz** [comment]
What do you mean by "fails for me" ?
