### ISSUE TITLE
Bug Query Logical operators Or

### ISSUE THREAD

**Issue by Deniel090** [luqasz/librouteros#121]
Hi there!

There is a bug with Or operator.

"NameError: name 'Or' is not defined"

Please fix it.
Thank You!

**Comment by luqasz** [comment]
I don't know:
* what you are doing (your code)
* traceback


If you don't provide more details e.g. traceback, I will not be able to help.
Take your time and write details what is going on. 
Writing like you did, does not help at all.

**Comment by Deniel090** [comment]
I tried this code sample from the docs:

name = Key('name')
disabled = Key('disabled')
for row in api.path('/interface').select(name, disabled).where(
        disabled == False,
        Or(
            name == 'ether2',
            name == 'wlan-lan',
            ),
        ):
        
..and the result was:
 
    Or(
NameError: name 'Or' is not defined

Without Or, works perfectly.

**Comment by luqasz** [comment]
python 101. import it
