### ISSUE TITLE
RouterOS 7 and wifiwave2 instead of wireless

### ISSUE THREAD

**Issue by ondrejbaranek** [luqasz/librouteros#126]
ROS 7 can now use interface wifiwave2 instead of wireless. Would it be possible to modify it accordingly?
Thank you!

**Comment by luqasz** [comment]
What do you mean by ?
> Would it be possible to modify it accordingly?

**Comment by ondrejbaranek** [comment]
i mean to modify librouteros to add support for wifiwave2 package if installed on routeros

**Comment by luqasz** [comment]
I haven't seen any changes in API so no problem there.
