### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by GNUtoo** [luqasz/librouteros#129]
Hi,

What is the exact license of what is in the librouteros git?

In the setup.py there is the following license: "GNU General Public License v2 (GPLv2)". Does that means that the license of librouterOS is GPLV2-only? Or does it means that the license is GPLv2-or-later?

This is important as I tried to add bundlewrap (a configuration management tool whose configuration can be written 100% in python) to the Guix distribution[1], and the issue is that bundlewrap is GPLv3 and it depends on librouteros.

So if librouterOS is GPLv2-only, I need to bugreport in bundlewrap and tell them not to use librouteros as GPLv2-only can't be combined with GPLv3 code.

If librouteros is GPLv2-or-later, even if bundlewrap has the same issue (we don't know if it's GPLv3-only or GPLv3-or-later) at least it would be fine to package both and to combine both together.

[1] https://issues.guix.gnu.org/55083

Denis.

**Comment by luqasz** [comment]
Hi

GPLv2 only.

**Comment by GNUtoo** [comment]
> GPLv2 only.
Thanks a lot for the clarification.

PS: I've tried to reply to the bug report by mail but apparently this didn't work.

Denis.

**Comment by luqasz** [comment]
For now I will stay with GPLv2 only. I don't mind if someone is using this library in their project. Even if it's BSD licensed etc. All I care about is that if someone wants to modify it, I'd like patches.

**Comment by emixa-d** [comment]
> For now I will stay with GPLv2 only. I don't mind if someone is using this library in their project. Even if it's BSD licensed etc. All I care about is that if someone wants to modify it, I'd like patches.

Does this include using librouteos in GPLv3 projects?

**Comment by luqasz** [comment]
> Does this include using librouteos in GPLv3-licensed projects?

Yes

**Comment by emixa-d** [comment]
> > Does this include using librouteos in GPLv3-licensed projects?
> 
> Yes

The problem is that the GPLv2-only is not compatible with the GPLv3, see <https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility>. So currently it does not appear to be legal for GPLv3-licensed projects to use the GPLv2-only-licensed.

**Comment by luqasz** [comment]
Well I was wrong. It is licensed in v2 and v3
https://github.com/luqasz/librouteros/blob/master/LICENSE#L242

**Comment by GNUtoo** [comment]
On Wed, 27 Apr 2022 15:20:55 -0700
Łukasz Kostka ***@***.***> wrote:

> Hi
Hi,

> GPLv2 only.

Thanks a lot for the clarification.

Denis.
