### ISSUE TITLE
OSPF passive checkbox

### ISSUE THREAD

**Issue by thefathacker** [luqasz/librouteros#130]
Hi Luqasv,

An issue I have found when attempt to add interface templates in ROS 7.2

running the following command
```
nbi = "lo0"
type = "ptp"
passive = False
area = "ospf2_area"
api.path("/routing/ospf/interface-template").add(interfaces=nbi.name, passive=passive, type=type, area=area)
```
I have found that passive is enabled not disabled

Additional when attempt to change this by
```
if("passive" in intf and not passive): api.path("/routing/ospf/interface-template").update(**{'.id':intf['.id'], 'passive':False})
```
This does not change the passive state.

Version Details:
Python 3.10.4 on Windows
librouteros latest via pip

Regards,

TFH

**Comment by luqasz** [comment]
```python
nbi = "lo0"
type = "ptp"
passive = False
area = "ospf2_area"
api.path("/routing/ospf/interface-template").add(interfaces=nbi.name, passive=passive, type=type, area=area)
```

`nbi` is a string variable. Strings don't have `name` attribute.

What does `api('/routing/ospf/interface-template/print')` show ?

**Comment by luqasz** [comment]
Found it.
```python
api('/routing/ospf/interface-template/unset', **{'.id': '*1', 'value-name':'passive'})
```
will unset `passive`
```python
api('/routing/ospf/interface-template/add', **{'area': 'backbone-v2','interfaces': 'LAN','type': 'ptp','passive':''})
```
will add with `passive`
