### ISSUE TITLE
Drop python 3.1, 3.2, 3.3 support

### ISSUE THREAD

**Issue by luqasz** [luqasz/librouteros#15]
Drop support for versions 3.0, 3.1 , 3.2 because:

- no `u''` which makes unicode handling difficult. 
- no 3.x versions of pytest.
- pydocstyle 2.0.0 depends on snowballstreamer which throws SyntaxError on python 3.2
- pytest does not have tmpdir_factory (`disk_image` fixture)

To do:

- [ ] remove unused `Decoder.decodeSentence()`
- [ ] replace decoding with `u''` in tests where possible

**Comment by hugovk** [comment]
Here's the pip installs for librouteros from PyPI for the last year -- no 3.0-3.2, and a single 3.3!
```
$ pypinfo -d 365 --percent --pip librouteros pyversion
python_version percent download_count
-------------- ------- --------------
2.7              48.4%          6,842
3.6              19.8%          2,804
3.5              18.2%          2,574
3.4              13.2%          1,861
2.6               0.4%             50
3.3               0.0%              1
```

Python 3.3 went EOL last month, you could consider dropping that too.

**Comment by luqasz** [comment]
Hi. 

Thx for info. Did no know that statistics. I will bump major version since it will break backwards compatibility.
