### ISSUE TITLE
ID Fields

### ISSUE THREAD

**Issue by nitrag** [luqasz/librouteros#20]
For `/ip/service/print`, the `.id` returns `*4` for SSH, which matches the ID in webfig.

When I go to change it with `/ip/service/set` though, it makes the change to ID `*6` (www-ssl) .

```python
def toggle_ssh(api, mode=False):
	services = api(cmd='/ip/service/print')
	ssh_port = 22
	ssh_id = 0
	for service in services:
		if service['name'] == 'ssh':
			ssh_port = service['port']
			ssh_id = service['.id']
			break
	params = {'disabled': (not mode), '.id': ssh_id}
	api(cmd='/ip/service/set', **params)
	return ssh_port

api(cmd='/ip/service/print')

params = {'disabled': False, '.id' :'4'}   <----
api(cmd='/ip/service/set', **params)

api(cmd='/ip/service/print')

params = {'disabled': True, '.id' :'4'}  <----
api(cmd='/ip/service/set', **params)

api(cmd='/ip/service/print')

```

**The README is incorrect**, you need to put the * in the ID field. Why, I don't know.

```python
params = {'disabled': True, '.id' :'*4'}
```

**Comment by luqasz** [comment]
Hi.

README gives a example in which id does not have any `*`. That is correct. Which does not mean that you always pass it as a integer. I will fix it. Thx for clarification.

  > For /ip/service/print, the .id returns *4 for SSH, which matches the ID in webfig.
When I go to change it with /ip/service/set though, it makes the change to ID *6 (www-ssl) .

If you do those operation within one session, ids can not change.

you need to ALWAYS use ids which API return. Exactly in that form.

**Comment by nitrag** [comment]
In the exact form. Got it. Thank you for this repo!
