### ISSUE TITLE
Update librouteros on PyPi

### ISSUE THREAD

**Issue by mrsmn** [luqasz/librouteros#24]
Hello there,

Just a heads up: librouteros' version on PyPi is still 1.0.4 so the usage instructions in the current README won't work.

```python
Traceback (most recent call last):
  File "librouteros_demo.py", line 4, in <module>
    from librouteros import login
ImportError: cannot import name login
```
Cheers.

**Comment by luqasz** [comment]
Thx. I've update default branch to 1.x
