### ISSUE TITLE
monitor traffic

### ISSUE THREAD

**Issue by Arave69** [luqasz/librouteros#243]
is there a way to use command line that monitors the traffic (rx-bits-per-second and tx-bits-per-second) such as in the Mikrotik help. If so what is the code for it?

https://help.mikrotik.com/docs/display/ROS/Interface+stats+and+monitor-traffic

**Comment by luqasz** [comment]
You can with `once=True` in a for loop.

**Comment by Arave69** [comment]
what is the correct syntax for the coding below?

```
from librouteros import connect

api = connect(
    username='user',
    password='password',
    host='192.168.1.1',
    )

interface = api.path('interface','monitor-traffic ether1 once')

tuple(interface)
for item in interface:
    print(item)
```

**Comment by luqasz** [comment]
Everything is in the docs. [readthedocs](https://librouteros.readthedocs.io/) with `once=True`.
