### ISSUE TITLE
query

### ISSUE THREAD

**Issue by mmamani** [luqasz/librouteros#25]
How should I express this command?

ip firewall address-list print where dynamic =yes

I try entering this command but I have an error

api(cmd='/ip/firewall/address-list/print', dynamic=true)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'true' is not defined

**Comment by luqasz** [comment]
Hi.

Currently there is no support / interface for any kind of query. I am working on it in #11.
For now you can:
```python
words = ('?=dynamic=yes')
api.protocol.writeSentence('/ip/firewall/address-list/print', *words)
self._readResponse()
```
Note that you need to convert any True, False into api representatives.
