### ISSUE TITLE
New authentication process in 6.43

### ISSUE THREAD

**Issue by slackr31337** [luqasz/librouteros#28]
What's new in 6.43rc19 (2018-May-25 08:48):

*) api - changed authentication process (https://wiki.mikrotik.com/wiki/Manual:API#Initial_login);

https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by Serphentas** [comment]
I'm willing to open a PR for this if nobody has started on a fix.

**Comment by luqasz** [comment]
Thx for information. I will try to figure something out so that no backwards compatibility is broken (ideally). PRs are welcome and we could figure something out together.

**Comment by luqasz** [comment]
I've created separate [branch](https://github.com/luqasz/librouteros/tree/6.43-auth) for new auth method. Please check it out and if you have any comments please share.

**Comment by Serphentas** [comment]
Thanks for the information. I will make sure to follow up once I have some free time, right now I'm busy with work.

Regarding the API version, yeah it's completely retarded. I've never seen such an archaic API (I guess MikroTik never heard of HTTP, JSON, etc.).

**Comment by luqasz** [comment]
I am not very happy with sending password in plain text first. This is a potential security flaw in versions with old auth method. Will see what I can do about this.

**Comment by Serphentas** [comment]
Perhaps send a "decoy" password just to see what kind of reply you get ? This would imply getting false failed login attempts in the logs.

**Comment by luqasz** [comment]
I've created PR https://github.com/luqasz/librouteros/pull/29
