### ISSUE TITLE
support for where

### ISSUE THREAD

**Issue by edelalva** [luqasz/librouteros#32]
Hi, new in Mikroitk, how do i make this command  'where' e.g.  /ip/hotspot/user/print where name='hello'.  Because I got a reply of 'no such command'. And this command works fine in command line. Thanks

**Comment by edelalva** [comment]
I got it the solution from other inquiry. Thanks.

**Comment by zentavr** [comment]
@edelalva I wonder what was the solution?

**Comment by zentavr** [comment]
from the [docs](https://wiki.mikrotik.com/wiki/Manual:API#Queries)
> Regular expressions are not supported in API, so do not try to send query with ~ symbol
Is #11 related to that?

Is the solution in [this](https://github.com/luqasz/librouteros/issues/25#issuecomment-361369519) comment?

**Comment by luqasz** [comment]
I do not plan to support any wrapper for regex. If you want to use `where` you can use [this](https://github.com/luqasz/librouteros/issues/25#issuecomment-361369519) workaroud. I will add a `rawQuerry()` method so it will be easier untill I develop more elegant solution.

**Comment by zentavr** [comment]
@luqasz unfortunately I need regexp here so this won’t work either

**Comment by luqasz** [comment]
How do you want me to support regex since API does not support it ?

**Comment by zentavr** [comment]
@luqasz no questions to you at all :)

**Comment by luqasz** [comment]
@zentavr I've added `rawCmd()` method for passing in custom commands. This will work for passing queries as well.
