### ISSUE TITLE
Api instance has no attribute 'run'

### ISSUE THREAD

**Issue by stmps** [luqasz/librouteros#33]
Hey guys,

I can't seem to "run" commands via this API. 
Ultimately I want to be able to add to an address list (/ip/firewall/address-list), but I can't even get as far as pulling down information from the router.

    import librouteros
    api = librouteros.connect(username=USERNAME, password=PASSWORD, host=HOSTNAME)
    addresses = api.run('/ip/address/print')
    print addresses
    api.close()

Results in:

    Traceback (most recent call last):
        [....]
        addresses = api.run('/ip/address/print')
    AttributeError: Api instance has no attribute 'run'

Running Python 2.7 and librouteros 2.1.0.

Any ideas? Thanks!

**Comment by luqasz** [comment]
https://github.com/luqasz/librouteros#usage

**Comment by stmps** [comment]
Hi @luqasz - I was working off the documentation suite at http://librouteros.readthedocs.io/en/latest/usage.html / https://github.com/luqasz/librouteros-docs.

For the benefit of future readers, the correct usage would be api(cmd='/ip/address/print').
