### ISSUE TITLE
dummy_user fills error log

### ISSUE THREAD

**Issue by Roman-Akopov** [luqasz/librouteros#38]
Hi,

The problem I want to discuss is that router log is filled with false positive messages about invalid logins. It looks like this

    system, error, critical    login failure for user dummy_user from 10.1.2.3 via api
    system, error, critical    login failure for user dummy_user from 10.1.2.3 via api
    system, error, critical    login failure for user dummy_user from 10.1.2.3 via api
    system, error, critical    login failure for user dummy_user from 10.1.2.3 via api
    system, error, critical    login failure for user dummy_user from 10.1.2.3 via api
    system, error, critical    login failure for user dummy_user from 10.1.2.3 via api
    system, info, account      user real_user logged in from 10.1.2.3 via api
    system, info, account      user real_user logged out from 10.1.2.3 via api

with error lines written in red. This makes router log less usable, as it is filled with a lot of noise. For instance I have router monitoring system which log in into router every minute and log is full with this error messages. I did not find any way to filter out errors for dummy_user in particular.

I think we need some "use_6_43_auth=None" parameter in connect method

    def connect(host, username, password, use_6_43_auth=None, **kwargs):

and argument based choice on what to do, maybe like this

    if use_6_43_auth is None:
        try:
            # First send dummy credentials to know if we get a =ret= back.
            # This way we know if it is a pre 6.43 auth method or not.
            sentence = api('/login', **{'name': 'dummy_user', 'password': 'dummy_password'})
            token = sentence[0]['ret']
        except (TrapError, MultiTrapError):
            # Login failed so use 6.43 auth method.
            api('/login', **{'name': username, 'password': password})
        except (ConnectionError, FatalError):
            transport.close()
            raise
        else:
            # We got =ret= so use pre 6.43 auth method.
            api('/login', **{'name': username, 'response': encode_password(token, password)})
    elif use_6_43_auth:
        api('/login', **{'name': username, 'password': password})
    else:
        api('/login', **{'name': username, 'response': encode_password(token, password)})

My proposal is that new parameter name is unique and can't be confused with anything. No existing code uses "use_6_43_auth". Google search by this name returns absolutely nothing right now. So you are safe adding this parameter. Also it has default value, so calling code requires no modifications.

Default value is None, not True or False. None corresponds to existing logic. So if calling code will not specify any value for use_6_43_auth parameter, then behavior will not change.

P.S. start of original discussion https://github.com/luqasz/librouteros/pull/29

**Comment by luqasz** [comment]
@Roman-Akopov Please review and comment (if any) for branch I've just pushed. I think this solution is a sweet spot for us both.

**Comment by Roman-Akopov** [comment]
> 
> 
> @Roman-Akopov Please review and comment (if any) for branch I've just pushed. I think this solution is a sweet spot for us both.

Looks good for me, thank you. I'd write a comment with description or just link to this issue to make it clear why "login_methods" parameter was introduced in the first place.
