### ISSUE TITLE
Problem with encoded

### ISSUE THREAD

**Issue by Mutilador** [luqasz/librouteros#39]
When I try the command api(cmd='/ip/neighbor/print') return this error:

  File "/home/HOME/.local/lib/python3.5/site-packages/librouteros/connections.py", line 164, in readWord
    return self.transport.read(length).decode(encoding=self.encoding, errors='strict')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 33: ordinal not in range(128)

**Comment by Mutilador** [comment]
I change default options in __init__.py to UTF-8 and same error:

    return self.transport.read(length).decode(encoding=self.encoding, errors='strict')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 33: invalid continuation byte

**Comment by luqasz** [comment]
Looks like you have already answered yourself in #40
