### ISSUE TITLE
fix broken pipe error by reconnecting to the mikrotik

### ISSUE THREAD

**Issue by engrbm87** [luqasz/librouteros#41]
Hello, is it possible add the functionality to reconnect to the mikrotik in case it was restarted. i am using home assistant and i get a broken pipe error if the mikrotik is rebooted. it can only be solved by restarting home assistant afterwards.
`File "/srv/homeassistant/lib/python3.5/site-packages/librouteros/api.py", line 79, in __call__
    self.protocol.writeSentence(cmd, *words)
  File "/srv/homeassistant/lib/python3.5/site-packages/librouteros/connections.py", line 139, in writeSentence
    self.transport.write(encoded)
  File "/srv/homeassistant/lib/python3.5/site-packages/librouteros/connections.py", line 185, in write
    raise ConnectionError('Failed to write to socket. ' + str(error))
librouteros.exceptions.ConnectionError: Failed to write to socket. [Errno 32] Broken pipe`

My suggestion is to try to create a new socket connection if we get connection error exception and then try to send the code again.
Thanks

**Comment by luqasz** [comment]
Hi. 
Thx for suggestion. I didn't implement any reconnecting feature on purpose. It requires library to manage state. Remember what is currently executed and what is more important, remember login credentials.

It certainly can be done but I am a bit hesitant to do this. For reasons listed above.
