### ISSUE TITLE
RouterOS hyphen keywords vs Python hyphen usage

### ISSUE THREAD

**Issue by avloboda** [luqasz/librouteros#45]
I would like to push out a new syslog config but I came across the below issue.

The specific code I tried to push was:
`result = api(cmd='/system/logging/action/add', name='testremove', target='remote', remote='172.16.0.4', bsd-syslog=True)`
This returned:
`SyntaxError: keyword can't be an expression`

I believe this has to do with the way RouterOS uses hyphens in keywords and with how the hyphen is reserved for the subtraction operator in python. Is there anyway around this issue? I looked through the wiki and did not see any similar examples.

**Comment by luqasz** [comment]
Just use params as dict.
```python
params = {'name':'testremove', 'target':'remote', 'remote':'172.16.0.4', 'bsd-syslog':True}
result = api(cmd='/system/logging/action/add', **params)
```

**Comment by avloboda** [comment]
Thank you!
