### ISSUE TITLE
Document how to connect without certificate installed on routeros

### ISSUE THREAD

**Issue by Omniflux** [luqasz/librouteros#46]
Documentation states that a certificate is required on routeros, however that is silly if you are just going to disable verification anyway.

Please document the proper configuration for connecting to routeros without an installed certificate.

```python
import ssl
from librouteros import connect
from librouteros.login import login_plain

ctx = ssl.create_default_context()
ctx.set_ciphers('ADH:@SECLEVEL=0')
ctx.check_hostname = False

api = connect(
    username='...',
    password='...',
    host='...',
    port=8729,
    login_methods=(login_plain,),
    ssl_wrapper=ctx.wrap_socket)
```

**Comment by luqasz** [comment]
`ctx.set_ciphers('ADH:@SECLEVEL=0')`
On what OS have you tested this ?

**Comment by Omniflux** [comment]
The setting is for OpenSSL 1.1.0+

I am using this on Debian 9.8.
