### ISSUE TITLE
trying to login with wrong credentials doesn't raise and error

### ISSUE THREAD

**Issue by engrbm87** [luqasz/librouteros#63]
If i try to login with a wrong username and password it keeps trying to connect and doesn't raise any error. i can see a LoginError Exception in the exceptions but it is not used.

**Comment by luqasz** [comment]
Please provide traceback and which version of routeros and which login_methods do you use.

**Comment by engrbm87** [comment]
I am using version 2.3.0 with login_method plain (Mikrotik is 6.45.3). If I use a wrong username or password it keeps trying to connect and doesn't raise any errors. Mikrotik log gets filled with login failure errors. i don't have any traceback because no errors are generated.

**Comment by luqasz** [comment]
Ah. Found the error. I'll fix it. Thx for reporting.
