### ISSUE TITLE
how to run script,3Q

### ISSUE THREAD

**Issue by cloudyan2012** [luqasz/librouteros#64]
![Screenshot_2019-09-22-14-04-15-832_com termux](https://user-images.githubusercontent.com/55647147/65383165-ba521680-dd43-11e9-8a34-e65bad020af0.png)
i want to run script ,but error,what should i do,help me,thank you

**Comment by luqasz** [comment]
- `rawCmd` is a method of `Api` class. 
- `?=name=smail` will not work with `run`. Query only works with `print`
