### ISSUE TITLE
Remove socket exceptions wrapping in create_transport()

### ISSUE THREAD

**Issue by luqasz** [luqasz/librouteros#70]

**Comment by engrbm87** [comment]
Hello @luqasz ,
Removig the exception wrapping is causing the socket timeout error not to raise an exception. Can you please clarify the reason for this modification here?

**Comment by luqasz** [comment]
HI
Can you please provide a example ? Also mind that some exceptions have changed name https://docs.python.org/3/library/socket.html#exceptions
I've removed it since it is redundant. Whenever some socket exception is raised, end user will catch it either way, so no need to raise custom exception.
