### ISSUE TITLE
File creation over API returns existing file instead of nothing. 

### ISSUE THREAD

**Issue by david-pili** [luqasz/librouteros#72]
RouterOS doesn't allow direct file creation from the API or CLI instead you have to  run something like `/file print file=myFile`
and it will create a new file with the name of myFile and nothing printed to the CLI

with the code 

`file = api.path('file')`
`tuple(file('print', **{'file':'"test10"'}))`

I get a tuple of all the existing files, it still creates the new file but I'm not sure why it's returning a tuple of existing files.

`tuple(file('set', **{'.id':'test10', 'contents':'testcontents'}))`

works as expected and returns an empty tuple and sets the contents of the file correctly.

**Comment by luqasz** [comment]
And what is the problem ?

**Comment by david-pili** [comment]
`tuple(file('print', **{'file':'"test10"'}))`

Should return an empty tuple, not a tuple of all files.

**Comment by luqasz** [comment]
Why, since you've requested API to do a `print` ?

**Comment by david-pili** [comment]
`tuple(file('print', **{'file':'"test10"'}))` should be the equivalent of `/file/print file=test10` which redirects the output of print to the file test10. Instead, it's returns the output of print to the API client and  creates an empty file named test10

Unless I'm not understanding how to use attribute words in your library the underlying API call should be 
`/file/print`
`=file=test10`

**Comment by luqasz** [comment]
API calls are not equivalent in 100% to cli commands.
API sends exactly:
```
/file/print
=file=test10
```
If you think this is a bug/shoule be changed, talk to MikroTik.
