### ISSUE TITLE
How to use find

### ISSUE THREAD

**Issue by pilotak** [luqasz/librouteros#75]
Throu terminal i use following command
`/ip firewall connection remove [find src-address~"^192.168.0.15:.*\$"]`

How am i going to use it in a path? following code gives me an error **no such command prefix**

```python
command = ['/ip', 'firewall', 'connection', 'remove', '[find src-address~"^192.168.0.15:.*\\$"]']
api.path(*command)
```

**Comment by luqasz** [comment]
Script does not work in API. You need to first e.g. use query and then remove.
