### ISSUE TITLE
Add API call timoeout

### ISSUE THREAD

**Issue by fenuks** [luqasz/librouteros#8]
Hello, could you consider adding timeout for api function call? Either in `Api` `__init__` or `__call__` method. Reasoning is as follows, there are some blocking calls, for instance `interface lte info lte1` that must be called prior to using `once` option of that command, or, as I experimentally checked, the response will be always empty. Perhaps, mikrotik has option for changing that behaviour, but unfortunately, I'm not aware of it. Thank you.

**Comment by luqasz** [comment]
Hi. You can set timeout when connecting with `timeout` parameter in `connect()`. There is no parameter exposed in `Api` class that corresponds to socket timeout. It can be changed in `api.protocol.transport.sock`. It is a standard python socket.

**Comment by fenuks** [comment]
Thank you for your prompt answer. Not exactly, the command from above never writes `'!done'` to the socket, therefore loop's condition in `_readResponse` method is never met. Therefore, what would I need is option to specify timeout of command, or even better, to not block waiting on response, since it will be never sent. Yet, one need to execute this command for version of command with `once` flag return data instead of empty response. It's clearly flaw in mikrotik API/command line, but I've checked it via ssh, and behaviour is the same – without prior executing `interface lte info lte1`, non-blocking version `interface lte info lte1 once` gives empty response.

**Comment by luqasz** [comment]
That would require usage of `.tag` but I did not implement it since I do not need that. As you've said, MikroTik API is verry buggy and flaw. What is worse that it is not versioned. `.tag` allow to use API in asynchronous mode and with synchronous code it can be difficult to implement this feature.

**Comment by luqasz** [comment]
@fenuks 

>Not exactly, the command from above never writes '!done' to the socket, therefore loop's condition in _readResponse method is never met. 

So mikrotik does not write `!done` to the socket when executing `api('/interface/lte/info', name='lte1')` ?

**Comment by luqasz** [comment]
Closing due to lack of response.
