### ISSUE TITLE
Question about socket connection

### ISSUE THREAD

**Issue by zzbe** [luqasz/librouteros#89]
Do you know if it's possible to check if socket/connection is still active so I don't have to (re)connect hundreds of times per day for every command?

**Comment by luqasz** [comment]
What is your use case ?

**Comment by zzbe** [comment]
I'm using it for Suricata IDS/IPS: pyinotify is reading from a file and then constantly adds IPs to address-list. For testing purposes I tried to only use 'api = connect(...)' once to see for how long that will work, but that didn't even work at all.
Anyway it's just minor annoyance - wanted to find a way to not pollute logs with lots of "user logged in" "user logged out".

**Comment by luqasz** [comment]
well it all depends on your program lifetime. it will connect whenever you run it so ...
