### ISSUE TITLE
Unable to specify '.id' attribute

### ISSUE THREAD

**Issue by etherfi** [luqasz/librouteros#9]
If I try to specify a target item ID, this happens:
>api(cmd='/ip/firewall/nat/print')
>api(cmd='/ip/firewall/nat/set', .id=7)                                                                                                                                                                          
>  File "<stdin>", line 1
>    pi(cmd='/ip/firewall/nat/set', disabled='yes', .id=7)
>SyntaxError: invalid syntax

That's because a keyword can't start with a period. However, when I try it without the period, this happens:

>api(cmd='/ip/firewall/nat/set', disabled='yes', id='7')
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python2.7/dist-packages/librouteros/api.py", line 80, in __call__
>    print words
>  File "/usr/local/lib/python2.7/dist-packages/librouteros/api.py", line 106, in _readResponse
>    response.append((reply_word, words))
>  File "/usr/local/lib/python2.7/dist-packages/librouteros/api.py", line 124, in _trapCheck
>    elif len(traps) == 1:
>librouteros.exceptions.TrapError: unknown parameter

Pisses me off that Mikrotik somehow reached the conclusion that starting ANY attribute with a period was a good idea, but I digress.

Am I doing something wrong?

**Comment by luqasz** [comment]
> Pisses me off that Mikrotik somehow reached the conclusion that starting ANY attribute with a period was a good idea, but I digress.
This is not the only part in API that is "confusing"

Try this:
```python
api(cmd='/ip/firewall/nat/set', **{'disabled': True, '.id' :'7'})
```
which is same as
```python
params = {'disabled': True, '.id' :'7'}
api(cmd='/ip/firewall/nat/set', **params)
```

`yes` , `no`, are transformed into booleans in library.
