### ISSUE TITLE
Is there a way to use 'where' filter, but not to use 'select' filter

### ISSUE THREAD

**Issue by amyasnikov** [luqasz/librouteros#91]
Let's suppose that I want to print all _interface vlan_ with _vlan-id=100_, but I need all available fields (not only name, .id or interface, but just all available fields).
So I want to run something like 
`print(*(i for i in path.select('').where(Key('vlan-id')==100)), sep='\n')`
and get all the fields from inerfaces with _vlan-id=100_ but I got nothing (iterator is empty).
Is there a way to make things this way in librouteros?

**Comment by luqasz** [comment]
So you want a equivalent of `SELECT * FROM TABLE;` ? 
Or just all possible key names ?

**Comment by amyasnikov** [comment]
I want equivalent of `SELECT * FROM table WHERE table.field1=1234`

**Comment by luqasz** [comment]
Currently there is no such possibility.
