### ISSUE TITLE
Iterating over generators gives confusing/unexpected results

### ISSUE THREAD

**Issue by Disassembler0** [luqasz/librouteros#94]
The code

```python
import librouteros
from pprint import pprint

api = librouteros.connect(host='192.168.x.y', username='user', password='pass')

for i in range(10):
    print(f'loop {i}')
    iface_path = api.path('interface')
    for iface in iface_path:
        if iface['name'] in ('ether1', 'ether2', 'ether3'):
            print(f'got {iface["name"]}')
            break

ip_path = api.path('ip', 'address')
print(ip_path)
pprint(tuple(ip_path))
```

gives following output:

```
loop 0
got ether1
loop 1
got ether2
loop 2
got ether3
loop 3
loop 4
got ether1
loop 5
got ether2
loop 6
got ether3
loop 7
loop 8
got ether1
loop 9
got ether2

<librouteros.api.Path '/ip/address'>

({'.id': '*2',
  'actual-mtu': 1500,
  'default-name': 'ether1',
  'disabled': False,
  'fp-rx-byte': 162821185,
  'fp-rx-packet': 848184,
  'fp-tx-byte': 204542918,
  'fp-tx-packet': 318617,
  'l2mtu': 1598,
  'last-link-up-time': 'jun/27/2020 16:05:47',
  'link-downs': 0,
  'mac-address': '6C:3B:6B:18:BE:30',
  'max-l2mtu': 4074,
  'mtu': 1500,
  'name': 'ether1',
  'running': True,
  'rx-byte': 12147401172,
  'rx-drop': 0,
  'rx-error': 0,
  'rx-packet': 9739159,
  'slave': True,
  'tx-byte': 514469607,
  'tx-drop': 0,
  'tx-error': 0,
  'tx-packet': 3885896,
  'tx-queue-drop': 0,
  'type': 'ether'},
...
```

It looks like when the generator isn't read until the end, it's reused on next read regardless of what path was supposed to be read. 

1) The `iface_path = api.path('interface')` is redefined on every loop, yet the underlying generator continues to generate like it's not.
2) After switching to a completely different path via `ip_path = api.path('ip', 'address')`, even though its *\_\_repr__* is correctly printed as `/ip/address`, it ***still*** continues to print data from the original generator for `/interface`.

Note that this can be mitigated using `for iface in tuple(iface_path):` instead of `for iface in iface_path:`, but that kinda defeats the purpose of using generators.

**Expected result:**
```
loop 0
got ether1
loop 1
got ether1
loop 2
got ether1
loop 3
got ether1
loop 4
got ether1
loop 5
got ether1
loop 6
got ether1
loop 7
got ether1
loop 8
got ether1
loop 9
got ether1
```
and the actual listing for `/ip/address` when `pprint(tuple(ip_path))` is called.

Observed on Python 3.8.2 + librouteros 3.0.0 + RouterOS 6.47.

**Comment by luqasz** [comment]
Thx for report. I need to think about how to fix it.

1. Always return from `Api.readResponse` without yielding. Defeats generator memory saving. Simple
2. Provide some request matching mechanism. Complex a bit, will store data even when generator is ditched, will save some memory.
